### ISSUE TITLE
Good Readme

### ISSUE THREAD

**Issue by elamandeep** [elamandeep/taskwise#4]
We need a good readme for our app. Please message on an issue if anyone wants to help on the readme.

**Comment by michaelmuthomi** [comment]
Hey, am interested in taking on this issue if available.

**Comment by SrNightmare09** [comment]
Hey, I am interested in taking up this issue. You can view the READMEs of my completed projects to judge my skills!

**Comment by elamandeep** [comment]
@SrNightmare09 and @michaelmuthomi why don't you write readme together?

**Comment by SrNightmare09** [comment]
@elamandeep i think what would be better is that we submit our respective readmes as a pr, from which you can choose the best one.

**Comment by elamandeep** [comment]
@SrNightmare09  great idea

**Comment by elamandeep** [comment]
> @elamandeep i think what would be better is that we submit our respective readmes as a pr, from which you can choose the best one.

kindly give us some time

**Comment by michaelmuthomi** [comment]
@SrNightmare09 I have committed a simple Readme in my Fork. Review it and make necessary changes or additions and add me as a coauthor in the pull request.

**Comment by elamandeep** [comment]
@michaelmuthomi  sure

**Comment by elamandeep** [comment]
@SrNightmare09 and @michaelmuthomi  are you on discord?

**Comment by SrNightmare09** [comment]
> @SrNightmare09 and @michaelmuthomi are you on discord?

yes

**Comment by michaelmuthomi** [comment]
> @SrNightmare09 and @michaelmuthomi are you on discord?

Yes

**Comment by elamandeep** [comment]
Here's my discord link. Join us on discord https://discord.com/users/788606884285251644

**Comment by elamandeep** [comment]
hey @michaelmuthomi  make a pull request. We are unable to merge it until u make a pull request

**Comment by michaelmuthomi** [comment]
@elamandeep  I have just Submitted the pull request

**Comment by elamandeep** [comment]
@michaelmuthomi  and @SrNightmare09  great work
